// Validates every question and writes questions/README.md.
//
//   node scripts/build-index.mjs           validate, then rewrite the index
//   node scripts/build-index.mjs --check   validate, and fail if the index is out of date

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { QUESTIONS_DIR, loadQuestions } from './lib/questions.mjs';

const INDEX = join(QUESTIONS_DIR, 'README.md');
const check = process.argv.includes('--check');

const { topics, questions, errors } = loadQuestions();
if (errors.length > 0) {
  console.error(`Found ${errors.length} problem(s):\n`);
  for (const error of errors) console.error(`  - ${error}`);
  process.exit(1);
}

const content = renderIndex(topics, questions);
const current = existsSync(INDEX) ? readFileSync(INDEX, 'utf8') : '';

if (check) {
  if (current !== content) {
    console.error('questions/README.md is out of date. Run "npm run index" and commit the result.');
    process.exit(1);
  }
  console.log(`OK: ${questions.length} questions, index up to date.`);
} else {
  if (current !== content) writeFileSync(INDEX, content);
  console.log(`Wrote questions/README.md (${questions.length} questions).`);
}

function renderIndex(topics, questions) {
  const totalMinutes = sum(questions.map(q => q.minutes));
  const lines = [
    '# Question index',
    '',
    '<!-- Generated by scripts/build-index.mjs. Do not edit by hand; run "npm run index". -->',
    '',
    `${questions.length} questions, about ${formatMinutes(totalMinutes)} of interview time.`,
    '',
    '| Topic | Questions | Time |',
    '| --- | --- | --- |',
  ];

  const populated = topics.filter(topic => questions.some(q => q.topic === topic.key));
  for (const topic of populated) {
    const own = questions.filter(q => q.topic === topic.key);
    lines.push(`| [${topic.title}](#${anchor(topic.title)}) | ${own.length} | ${formatMinutes(sum(own.map(q => q.minutes)))} |`);
  }

  for (const topic of populated) {
    const own = questions
      .filter(q => q.topic === topic.key)
      .sort((a, b) => a.id.localeCompare(b.id, 'en', { numeric: true }));
    lines.push('', `## ${topic.title}`, '', topic.description, '');
    lines.push('| ID | Question | Format | Level | Minutes | Tags |', '| --- | --- | --- | --- | --- | --- |');
    for (const q of own) {
      const link = q.file.replace(/^questions\//, '');
      const tags = q.tags.map(tag => `\`${tag}\``).join(' ');
      lines.push(`| ${q.id} | [${escapeCell(q.title)}](${link}) | ${q.format} | ${q.difficulty} | ${q.minutes} | ${tags} |`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function sum(values) {
  return values.reduce((total, value) => total + value, 0);
}

function formatMinutes(minutes) {
  const hours = Math.floor(minutes / 60);
  const rest = minutes % 60;
  if (hours === 0) return `${rest} min`;
  return rest === 0 ? `${hours} h` : `${hours} h ${rest} min`;
}

// Matches GitHub's heading anchors for the plain-text titles used in topics.json.
function anchor(title) {
  return title.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/ /g, '-');
}

function escapeCell(text) {
  return text.replace(/\|/g, '\\|');
}
